### ISSUE TITLE
Video unsupported issue

### ISSUE THREAD

**Issue by SHADOW-REX** [REVENGE977/stremio-enhanced#22]
**Describe the bug**
I downloaded stremio enhanced using aur and have no enhanced option.

**Expected behavior**
Get the option for enhanced settings.

**Screenshots**
![Image](https://github.com/user-attachments/assets/8267fb90-a3a0-46df-9279-6db5efa97a44)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: v0.9

**Comment by REVENGE977** [comment]
This issue was likely caused by the app looking for the APPDATA folder (using process.env.APPDATA), which doesn’t exist on Linux. I’ve fixed this in [v0.9.1](https://github.com/REVENGE977/stremio-enhanced/releases/tag/v0.9.1), so feel free to update and see if that fixes the issue.

**Comment by SHADOW-REX** [comment]
Okay let me try, also the version on which I created this issue most files I tried to play said video not supported. Is that also because of this only?

**Comment by SHADOW-REX** [comment]
> "video not supported" usually happens because of a problem in Stremio Service. Try downloading [linux-unpacked-service-bundled.zip](https://github.com/REVENGE977/stremio-enhanced/releases/download/v20250413182358/linux-unpacked-service-bundled.zip) see if that fixes it.

Tried the bundled zip, enhanced options are now available but video still shows as not supported.
Some output snippets:

- This one is stremio-enhanced:
```
❯ ./stremio-enhanced
INFO: Enhanced version: v0.9.1
INFO: Running on NodeJS version: v18.18.2
INFO: Running on Electron version: v28.3.3
INFO: Running on Chromium version: v120.0.6099.291
INFO: User data path: /home/shado/.config/stremio-enhanced
INFO: Themes path: /home/shado/.config/stremio-enhanced/themes
INFO: Plugins path: /home/shado/.config/stremio-enhanced/plugins
INFO: [ StremioService ] StremioService executable found in the current directory.
INFO: Stremio Service is already running.
INFO: [ StremioService ] Terminating Stremio Service.
INFO: [ StremioService ] Stremio Service terminated.
```

- This one is stremio-service logs:
```
❯ ./stremio-service
[2025-04-14T10:51:12Z INFO  stremio_service] Using service configuration: Config {
        home_dir: "/home/shado",
        lockfile: "/home/shado/.cache/lock",
        server: Config {
            server: "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js",
            node: "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/stremio-runtime",
            ffmpeg: "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/ffmpeg",
            ffprobe: "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/ffprobe",
        },
        updater_endpoint: Url {
            scheme: "https",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: Some(
                Domain(
                    "www.strem.io",
                ),
            ),
            port: None,
            path: "/updater/check",
            query: Some(
                "product=stremio-service",
            ),
            fragment: None,
        },
        skip_update: false,
        force_update: false,
    }
[2025-04-14T10:51:12Z INFO  stremio_service::server] Starting server.js: Command {
        program: "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/stremio-runtime",
        args: [
            "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/stremio-runtime",
            "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js",
        ],
        env: CommandEnv {
            clear: false,
            vars: {
                "FFMPEG_BIN": Some(
                    "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/ffmpeg",
                ),
                "FFPROBE_BIN": Some(
                    "/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/ffprobe",
                ),
            },
        },
        create_pidfd: false,
    }
[2025-04-14T10:51:12Z INFO  stremio_service::server] Server started. (PID 2266319)

(stremio-service:2266292): Gtk-CRITICAL **: 16:21:12.733: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
hls executables located ->  {
  ffmpeg: '/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/ffmpeg',
  ffsplit: null,
  ffprobe: '/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/ffprobe'
}
Using app path -> /home/shado/.stremio-server
Enabling casting...
Discovery of new external device "vlc" - VLC
Discovery of new external device "mpv" - MPV
(node:2266319) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470
-> GET /settings
-> GET /casting
-> GET /network-info
-> GET /device-info
-> GET /settings
-> GET /casting
-> GET /network-info
-> GET /device-info
-> GET /hlsv2/probe?mediaURL=https%3A%2F%2Fcomet.elfhosted.com%2FeyJtYXhSZXN1bHRzUGVyUmVzb2x1dGlvbiI6MCwibWF4U2l6ZSI6MCwiY2FjaGVkT25seSI6ZmFsc2UsInJlbW92ZVRyYXNoIjpmYWxzZSwicmVzdWx0Rm9ybWF0IjpbImFsbCJdLCJkZWJyaWRTZXJ2aWNlIjoicmVhbGRlYnJpZCIsImRlYnJpZEFwaUtleSI6IkxQUkVTNzVST0JQNlRaM01NUEhaTUpaTjVWRjQyNEYyNktXNDNVU0dFREpFQzZINElTWUEiLCJkZWJyaWRTdHJlYW1Qcm94eVBhc3N3b3JkIjoiIiwibGFuZ3VhZ2VzIjp7InJlcXVpcmVkIjpbXSwiZXhjbHVkZSI6W10sInByZWZlcnJlZCI6W119LCJyZXNvbHV0aW9ucyI6e30sIm9wdGlvbnMiOnsicmVtb3ZlX3JhbmtzX3VuZGVyIjotMTAwMDAwMDAwMDB9fQ%3D%3D%2Fplayback%2F01816cdeaced14530056f39fd2b62aed3775d827%2F1%2Ftransformers%2520rise%2520of%2520the%2520beasts%2Fn%2Fn%2FTransformers.Rise.of.the.Beasts.2023.BluRay.2160p.UHD.MULTi.REMUX.HEVC.%2810bit%29.DV.Atmos.DTS-HD.MA.7.1-LEGi0N.mkv
Error: Probe process has been terminated with signal: SIGSEGV
    at EventEmitter.<anonymous> (/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js:29830:65)
    at Object.onceWrapper (node:events:628:26)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js:65184:37)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
-> HEAD /hlsv2/ad63983c9ebe625e33d7db43522f49d8/master.m3u8?mediaURL=https%3A%2F%2Fcomet.elfhosted.com%2FeyJtYXhSZXN1bHRzUGVyUmVzb2x1dGlvbiI6MCwibWF4U2l6ZSI6MCwiY2FjaGVkT25seSI6ZmFsc2UsInJlbW92ZVRyYXNoIjpmYWxzZSwicmVzdWx0Rm9ybWF0IjpbImFsbCJdLCJkZWJyaWRTZXJ2aWNlIjoicmVhbGRlYnJpZCIsImRlYnJpZEFwaUtleSI6IkxQUkVTNzVST0JQNlRaM01NUEhaTUpaTjVWRjQyNEYyNktXNDNVU0dFREpFQzZINElTWUEiLCJkZWJyaWRTdHJlYW1Qcm94eVBhc3N3b3JkIjoiIiwibGFuZ3VhZ2VzIjp7InJlcXVpcmVkIjpbXSwiZXhjbHVkZSI6W10sInByZWZlcnJlZCI6W119LCJyZXNvbHV0aW9ucyI6e30sIm9wdGlvbnMiOnsicmVtb3ZlX3JhbmtzX3VuZGVyIjotMTAwMDAwMDAwMDB9fQ%3D%3D%2Fplayback%2F01816cdeaced14530056f39fd2b62aed3775d827%2F1%2Ftransformers%2520rise%2520of%2520the%2520beasts%2Fn%2Fn%2FTransformers.Rise.of.the.Beasts.2023.BluRay.2160p.UHD.MULTi.REMUX.HEVC.%2810bit%29.DV.Atmos.DTS-HD.MA.7.1-LEGi0N.mkv&videoCodecs=h264&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=32
Error: Probe process has been terminated with signal: SIGSEGV
    at EventEmitter.<anonymous> (/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js:29830:65)
    at Object.onceWrapper (node:events:628:26)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js:65184:37)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
-> GET /hlsv2/ad63983c9ebe625e33d7db43522f49d8/master.m3u8?mediaURL=https%3A%2F%2Fcomet.elfhosted.com%2FeyJtYXhSZXN1bHRzUGVyUmVzb2x1dGlvbiI6MCwibWF4U2l6ZSI6MCwiY2FjaGVkT25seSI6ZmFsc2UsInJlbW92ZVRyYXNoIjpmYWxzZSwicmVzdWx0Rm9ybWF0IjpbImFsbCJdLCJkZWJyaWRTZXJ2aWNlIjoicmVhbGRlYnJpZCIsImRlYnJpZEFwaUtleSI6IkxQUkVTNzVST0JQNlRaM01NUEhaTUpaTjVWRjQyNEYyNktXNDNVU0dFREpFQzZINElTWUEiLCJkZWJyaWRTdHJlYW1Qcm94eVBhc3N3b3JkIjoiIiwibGFuZ3VhZ2VzIjp7InJlcXVpcmVkIjpbXSwiZXhjbHVkZSI6W10sInByZWZlcnJlZCI6W119LCJyZXNvbHV0aW9ucyI6e30sIm9wdGlvbnMiOnsicmVtb3ZlX3JhbmtzX3VuZGVyIjotMTAwMDAwMDAwMDB9fQ%3D%3D%2Fplayback%2F01816cdeaced14530056f39fd2b62aed3775d827%2F1%2Ftransformers%2520rise%2520of%2520the%2520beasts%2Fn%2Fn%2FTransformers.Rise.of.the.Beasts.2023.BluRay.2160p.UHD.MULTi.REMUX.HEVC.%2810bit%29.DV.Atmos.DTS-HD.MA.7.1-LEGi0N.mkv&videoCodecs=h264&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=32 bytes=0-
Error: Probe process has been terminated with signal: SIGSEGV
    at EventEmitter.<anonymous> (/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js:29830:65)
    at Object.onceWrapper (node:events:628:26)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/home/shado/Downloads/stremio-enhanced/stremio-enhanced-linux-x64-service-bundled/server.js:65184:37)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)```

**Comment by REVENGE977** [comment]
**Thank you for providing logs.**

It seems something is causing ffprobe to terminate unexpectedly.

- Check whether you have the Stremio Service status Online or Offline in the settings before playing a video

![Image](https://github.com/user-attachments/assets/94a0940c-6b23-4530-ae6a-47302c1b6e42)

- Also, check the DevTools console for any errors. (<kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> to open DevTools).

- One thing you can also try is installing Stremio Service through Flatpak and using [the build that doesn't have Stremio Service bundled](https://github.com/REVENGE977/stremio-enhanced/releases/download/v20250413182358/linux-unpacked.zip). Maybe the bundled ffmpeg/ffprobe binaries aren't compatible with your system for whatever reason, so Flatpak should make sure you have the necessary dependencies downloaded.

- Another thing is try to run Stremio Service alone (without running Enhanced) and open https://web.stremio.com/ in your browser. See if videos work fine in the web version in your browser. This is to determine whether the issue is from Stremio Service or Enhanced.

I can't seem to replicate this issue on an Arch Linux VM, so all I can do is suggest troubleshooting steps.

**Comment by SHADOW-REX** [comment]
### Your Welcome 
As for the checks:

- Stremio Service status was online (failed)
- Error in console upon starting stremio:
```
Shell.js:21 Qt API not found
_ @ Shell.js:21
web.stremio.com/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://web.stremio.com/f451af161c8f14909eff62081bbb97f3ab291574/fonts/PlusJakartaSans.ttf
getVisibleChildrenRange.js:4 Specifying 'overflow: visible' on img, video and canvas tags may cause them to produce visual content outside of the element bounds. See https://github.com/WICG/view-transitions/blob/main/debugging_overflow_on_images.md for details.
(anonymous) @ getVisibleChildrenRange.js:4
/home/shado/Downloads/stremio-enhanced-linux-x64-service-bundled/resources/app.asar/node_modules/winston/lib/winston/transports/console.js:82 INFO: [ Updater ] Latest version available is v0.9.1.
/home/shado/Downloads/stremio-enhanced-linux-x64-service-bundled/resources/app.asar/node_modules/winston/lib/winston/transports/console.js:82 INFO: Stremio streaming server reloaded.
node:events:517 INFO: Adding 'Enhanced' sections...
node:events:517 INFO: [ Settings ] Adding section: enhanced with title: Enhanced
node:events:517 INFO: [ Settings ] Adding category: Themes to section: enhanced
node:events:517 INFO: [ Settings ] Adding category: Plugins to section: enhanced
node:events:517 INFO: [ Settings ] Adding category: About to section: enhanced
node:events:517 INFO: [ ModManager ] Listening to plugin checkboxes...
useVideo.js:47 
        
        
       GET http://127.0.0.1:11470/hlsv2/probe?mediaURL=https%3A%2F%2Fcomet.elfhosted.com%2FeyJtYXhSZXN1bHRzUGVyUmVzb2x1dGlvbiI6MCwibWF4U2l6ZSI6MCwiY2FjaGVkT25seSI6ZmFsc2UsInJlbW92ZVRyYXNoIjpmYWxzZSwicmVzdWx0Rm9ybWF0IjpbImFsbCJdLCJkZWJyaWRTZXJ2aWNlIjoicmVhbGRlYnJpZCIsImRlYnJpZEFwaUtleSI6IkxQUkVTNzVST0JQNlRaM01NUEhaTUpaTjVWRjQyNEYyNktXNDNVU0dFREpFQzZINElTWUEiLCJkZWJyaWRTdHJlYW1Qcm94eVBhc3N3b3JkIjoiIiwibGFuZ3VhZ2VzIjp7InJlcXVpcmVkIjpbXSwiZXhjbHVkZSI6W10sInByZWZlcnJlZCI6W119LCJyZXNvbHV0aW9ucyI6e30sIm9wdGlvbnMiOnsicmVtb3ZlX3JhbmtzX3VuZGVyIjotMTAwMDAwMDAwMDB9fQ%3D%3D%2Fplayback%2F01816cdeaced14530056f39fd2b62aed3775d827%2F1%2Ftransformers%2520rise%2520of%2520the%2520beasts%2Fn%2Fn%2FTransformers.Rise.of.the.Beasts.2023.BluRay.2160p.UHD.MULTi.REMUX.HEVC.%2810bit%29.DV.Atmos.DTS-HD.MA.7.1-LEGi0N.mkv 500 (Internal Server Error)
(anonymous) @ withStreamingServer.js:360
Promise.then (async)
t.canPlayStream @ withStreamingServer.js:353
(anonymous) @ withStreamingServer.js:134
Promise.then (async)
h @ withStreamingServer.js:108
dispatch @ withStreamingServer.js:338
T.dispatch @ StremioVideo.js:84
_ @ useVideo.js:47
load @ useVideo.js:58
(anonymous) @ Player.js:293
i_ @ react-dom.production.min.js:243
LT @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
L @ scheduler.production.min.js:13
g @ scheduler.production.min.js:14
processImmediate @ node:internal/timers:476
Show 11 more frames
Show less
useVideo.js:47 
        
        
       HEAD http://127.0.0.1:11470/hlsv2/850db5cad8c06a6b24ab2a192e727f0b/master.m3u8?mediaURL=https%3A%2F%2Fcomet.elfhosted.com%2FeyJtYXhSZXN1bHRzUGVyUmVzb2x1dGlvbiI6MCwibWF4U2l6ZSI6MCwiY2FjaGVkT25seSI6ZmFsc2UsInJlbW92ZVRyYXNoIjpmYWxzZSwicmVzdWx0Rm9ybWF0IjpbImFsbCJdLCJkZWJyaWRTZXJ2aWNlIjoicmVhbGRlYnJpZCIsImRlYnJpZEFwaUtleSI6IkxQUkVTNzVST0JQNlRaM01NUEhaTUpaTjVWRjQyNEYyNktXNDNVU0dFREpFQzZINElTWUEiLCJkZWJyaWRTdHJlYW1Qcm94eVBhc3N3b3JkIjoiIiwibGFuZ3VhZ2VzIjp7InJlcXVpcmVkIjpbXSwiZXhjbHVkZSI6W10sInByZWZlcnJlZCI6W119LCJyZXNvbHV0aW9ucyI6e30sIm9wdGlvbnMiOnsicmVtb3ZlX3JhbmtzX3VuZGVyIjotMTAwMDAwMDAwMDB9fQ%3D%3D%2Fplayback%2F01816cdeaced14530056f39fd2b62aed3775d827%2F1%2Ftransformers%2520rise%2520of%2520the%2520beasts%2Fn%2Fn%2FTransformers.Rise.of.the.Beasts.2023.BluRay.2160p.UHD.MULTi.REMUX.HEVC.%2810bit%29.DV.Atmos.DTS-HD.MA.7.1-LEGi0N.mkv&videoCodecs=h264&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=32 500 (Internal Server Error)
(anonymous) @ getContentType.js:10
L @ HTMLVideo.js:522
S.dispatch @ HTMLVideo.js:646
dispatch @ withHTMLSubtitles.js:518
(anonymous) @ withStreamingServer.js:198
Promise.then (async)
h @ withStreamingServer.js:193
dispatch @ withStreamingServer.js:338
T.dispatch @ StremioVideo.js:84
_ @ useVideo.js:47
load @ useVideo.js:58
(anonymous) @ Player.js:293
i_ @ react-dom.production.min.js:243
LT @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
L @ scheduler.production.min.js:13
g @ scheduler.production.min.js:14
processImmediate @ node:internal/timers:476
Show 13 more frames
Show less
/#/player/eAEBAQX%2B%2BnsidXJsIjoiaHR0cHM6Ly9jb21ldC5lbGZob3N0ZWQuY29tL2V5SnRZWGhTWlhOMWJIUnpVR1Z5VW1WemIyeDFkR2x2YmlJNk1Dd2liV0Y0VTJsNlpTSTZNQ3dpWTJGamFHVmtUMjVzZVNJNlptRnNjMlVzSW5KbGJXOTJaVlJ5WVhOb0lqcG1ZV3h6WlN3aWNtVnpkV3gwUm05eWJXRjBJanBiSW1Gc2JDSmRMQ0prWldKeWFXUlRaWEoyYVdObElqb2ljbVZoYkdSbFluSnBaQ0lzSW1SbFluSnBaRUZ3YVV0bGVTSTZJa3hRVWtWVE56VlNUMEpRTmxSYU0wMU5VRWhhVFVwYVRqVldSalF5TkVZeU5rdFhORE5WVTBkRlJFcEZRelpJTkVsVFdVRWlMQ0prWldKeWFXUlRkSEpsWVcxUWNtOTRlVkJoYzNOM2IzSmtJam9pSWl3aWJHRnVaM1ZoWjJWeklqcDdJbkpsY1hWcGNtVmtJanBiWFN3aVpYaGpiSFZrWlNJNlcxMHNJbkJ5WldabGNuSmxaQ0k2VzExOUxDSnlaWE52YkhWMGFXOXVjeUk2ZTMwc0ltOXdkR2x2Ym5NaU9uc2ljbVZ0YjNabFgzSmhibXR6WDNWdVpHVnlJam90TVRBd01EQXdNREF3TURCOWZRPT0vcGxheWJhY2svMDE4MTZjZGVhY2VkMTQ1MzAwNTZmMzlmZDJiNjJhZWQzNzc1ZDgyNy8xL3RyYW5zZm9ybWVycyUyMHJpc2UlMjBvZiUyMHRoZSUyMGJlYXN0cy9uL24vVHJhbnNmb3JtZXJzLlJpc2Uub2YudGhlLkJlYXN0cy4yMDIzLkJsdVJheS4yMTYwcC5VSEQuTVVMVGkuUkVNVVguSEVWQy4oMTBiaXQpLkRWLkF0bW9zLkRUUy1IRC5NQS43LjEtTEVHaTBOLm1rdiIsIm5hbWUiOiJbUkTimqFdXG5Db21ldCAyMTYwcCIsImRlc2NyaXB0aW9uIjoi8J%2BOpSBCbHVSYXkg8J%2BOnu%2B4jyBIRVZDIFxu8J%2BTuiAxMGJpdCB8IERWICAg8J%2BOpyBBdG1vcyB8IERUUy1IRCBNQSB8IDcuMVxu8J%2BTpiA2OC41NiBHaUIg8J%2BUjSBUb3JyZW50aW98S25pZ2h0Q3Jhd2xlclxu8J%2BUiiBNdWx0aVxu8J%2BThCBUcmFuc2Zvcm1lcnMuUmlzZS5vZi50aGUuQmVhc3RzLjIwMjMuQmx1UmF5LjIxNjBwLlVIRC5NVUxUaS5SRU1VWC5IRVZDLigxMGJpdCkuRFYuQXRtb3MuRFRTLUhELk1BLjcuMS1MRUdpME4ubWt2IiwiYmVoYXZpb3JIaW50cyI6eyJiaW5nZUdyb3VwIjoiYWlvc3RyZWFtcy52aXJlbjA3MC5jb218Q29tZXR8MjE2MHB8Qmx1UmF5fEhFVkN8MTBiaXR8RFZ8QXRtb3N8RFRTLUhEIE1BfDcuMXxNdWx0aSIsImZpbGVuYW1lIjoiVHJhbnNmb3JtZXJzLlJpc2Uub2YudGhlLkJlYXN0cy4yMDIzLkJsdVJheS4yMTYwcC5VSEQuTVVMVGkuUkVNVVguSEVWQy4oMTBiaXQpLkRWLkF0bW9zLkRUUy1IRC5NQS43LjEtTEVHaTBOLm1rdiIsInZpZGVvU2l6ZSI6NzM2MjAyOTY1MzN9fT8fsJg%3D/https%3A%2F%2Faiostreams.elfhosted.com%2FE2-mlp1dcZyBdYDJyCY0NJY0g%253D%253D-x1aTgYyE4mJrKHgeeYytm%252Baxv2v9Yul%252FOQ8M5f1na03TLI4g9h%252BajKqETLJfNHnSK5d%252BbubVk8x6Bf382iwKAODg0qWpUQHLuh82fVCANiR2EOQqMvuAEs3k%252BqJ7clSg%252BuueTj6CxZmJuMRhYjstAs9%252ByNGqDHuppGljL%252B5pWxwzTkSGvC%252BAlYYKeu3OMxEWtHruNXa6efzXJpy8lOl8pfbRVA6TLcJ%252Fm2sHTexUsFJSbUW7vLXoaa%252BQy5V4ztOfc%252BPOFfKHPRdAKa%252BKLfkOiRYLLZnWyvqFhHEun8%252FQNtPi45RRbJUDylGU2oOCCs3zGHpb2YVi%252F4bUS1gan2kLEg1GdML5PN378lPyckjDv6%252FfEKx8GK2wSuwlSn7ALNZyUlB2dtO9w5IUn6vGeUOFt0VocfS16BX0%252BN5SROzutVda9FHjvB8QkpyDNDXHIiB04q5a6y9sxP8CSj9hvUaHnDTasUE7ShHSbhLxPsGCSPqntEROc6n012DRFfq87dCSg3aIb92ukd5SOhZsAd6ZyTLfuvdHgiKZeK5V6EGyt%252BE%252FLbnpVVoZ6hG0l%252B1EFuDEJZC1erTMHDhcf%252BvGM%252BM972x9n5utFAfsYxxL1AGQ5rJQgFHIQtrreE4ytrBEmK5Cs9jHvJEnUAlxEvhg7z8M3CslsQHtWIT6fol1C%252BZQjLqrfP3aJ%252BEgquJA%252BYJ%252FuVigYVUgvn1V%252FGs7zPC%252BXx%252FJq2F%252BoBNyXzsTRqh%252BPoO6jCtjouQtonnKran28ie2gPQx5ktESu72bq%252FyH2o%252Bmw23VA%253D%253D%2Fmanifest.json/https%3A%2F%2F94c8cb9f702d-tmdb-addon.baby-beamup.club%2F%257B%2522ratings%2522%253A%2522on%2522%252C%2522rpdbkey%2522%253A%2522t0-free-rpdb%2522%252C%2522provide_imdbId%2522%253A%2522true%2522%252C%2522use_tmdb_prefix%2522%253A%2522true%2522%252C%2522include_adult%2522%253A%2522true%2522%252C%2522language%2522%253A%2522en-US%2522%252C%2522sessionId%2522%253A%2522604eece08a2c081075081928d7cbe49d77a33bd2%2522%257D%2Fmanifest.json/movie/tmdb%3A667538/tt5090568:1 Mixed Content: The page at 'https://web.stremio.com/#/player/eAEBAQX%2B%2BnsidXJsIjoiaHR0cHM6Ly9jb21ldC5lbGZob3N0ZWQuY29tL2V5SnRZWGhTWlhOMWJIUnpVR1Z5VW1WemIyeDFkR2x2YmlJNk1Dd2liV0Y0VTJsNlpTSTZNQ3dpWTJGamFHVmtUMjVzZVNJNlptRnNjMlVzSW5KbGJXOTJaVlJ5WVhOb0lqcG1ZV3h6WlN3aWNtVnpkV3gwUm05eWJXRjBJanBiSW1Gc2JDSmRMQ0prWldKeWFXUlRaWEoyYVdObElqb2ljbVZoYkdSbFluSnBaQ0lzSW1SbFluSnBaRUZ3YVV0bGVTSTZJa3hRVWtWVE56VlNUMEpRTmxSYU0wMU5VRWhhVFVwYVRqVldSalF5TkVZeU5rdFhORE5WVTBkRlJFcEZRelpJTkVsVFdVRWlMQ0prWldKeWFXUlRkSEpsWVcxUWNtOTRlVkJoYzNOM2IzSmtJam9pSWl3aW...q%252FyH2o%252Bmw23VA%253D%253D%2Fmanifest.json/https%3A%2F%2F94c8cb9f702d-tmdb-addon.baby-beamup.club%2F%257B%2522ratings%2522%253A%2522on%2522%252C%2522rpdbkey%2522%253A%2522t0-free-rpdb%2522%252C%2522provide_imdbId%2522%253A%2522true%2522%252C%2522use_tmdb_prefix%2522%253A%2522true%2522%252C%2522include_adult%2522%253A%2522true%2522%252C%2522language%2522%253A%2522en-US%2522%252C%2522sessionId%2522%253A%2522604eece08a2c081075081928d7cbe49d77a33bd2%2522%257D%2Fmanifest.json/movie/tmdb%3A667538/tt5090568' was loaded over HTTPS, but requested an insecure element 'http://127.0.0.1:11470/hlsv2/850db5cad8c06a6b24ab2a192e727f0b/master.m3u8?mediaURL=https%3A%2F%2Fcomet.elfhosted.com%2FeyJtYXhSZXN1bHRzUGVyUmVzb2x1dGlvbiI6MCwibWF4U2l6ZSI6MCwiY2FjaGVkT25seSI6ZmFsc2UsInJlbW92ZVRyYXNoIjpmYWxzZSwicmVzdWx0Rm9ybWF0IjpbImFsbCJdLCJkZWJyaWRTZXJ2aWNlIjoicmVhbGRlYnJpZCIsImRlYnJpZEFwaUtleSI6IkxQUkVTNzVST0JQNlRaM01NUEhaTUpaTjVWRjQyNEYyNktXNDNVU0dFREpFQzZINElTWUEiLCJkZWJyaWRTdHJlYW1Qcm94eVBhc3N3b3JkIjoiIiwibGFuZ3VhZ2VzIjp7InJlcXVpcmVkIjpbXSwiZXhjbHVkZSI6W10sInByZWZlcnJlZCI6W119LCJyZXNvbHV0aW9ucyI6e30sIm9wdGlvbnMiOnsicmVtb3ZlX3JhbmtzX3VuZGVyIjotMTAwMDAwMDAwMDB9fQ%3D%3D%2Fplayback%2F01816cdeaced14530056f39fd2b62aed3775d827%2F1%2Ftransformers%2520rise%2520of%2520the%2520beasts%2Fn%2Fn%2FTransformers.Rise.of.the.Beasts.2023.BluRay.2160p.UHD.MULTi.REMUX.HEVC.%2810bit%29.DV.Atmos.DTS-HD.MA.7.1-LEGi0N.mkv&videoCodecs=h264&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=32'. This request was not upgraded to HTTPS because its URL's host is an IP address.
master.m3u8:1 
        
        
       GET http://127.0.0.1:11470/hlsv2/850db5cad8c06a6b24ab2a192e727f0b/master.m3u8?mediaURL=https%3A%2F%2Fcomet.elfhosted.com%2FeyJtYXhSZXN1bHRzUGVyUmVzb2x1dGlvbiI6MCwibWF4U2l6ZSI6MCwiY2FjaGVkT25seSI6ZmFsc2UsInJlbW92ZVRyYXNoIjpmYWxzZSwicmVzdWx0Rm9ybWF0IjpbImFsbCJdLCJkZWJyaWRTZXJ2aWNlIjoicmVhbGRlYnJpZCIsImRlYnJpZEFwaUtleSI6IkxQUkVTNzVST0JQNlRaM01NUEhaTUpaTjVWRjQyNEYyNktXNDNVU0dFREpFQzZINElTWUEiLCJkZWJyaWRTdHJlYW1Qcm94eVBhc3N3b3JkIjoiIiwibGFuZ3VhZ2VzIjp7InJlcXVpcmVkIjpbXSwiZXhjbHVkZSI6W10sInByZWZlcnJlZCI6W119LCJyZXNvbHV0aW9ucyI6e30sIm9wdGlvbnMiOnsicmVtb3ZlX3JhbmtzX3VuZGVyIjotMTAwMDAwMDAwMDB9fQ%3D%3D%2Fplayback%2F01816cdeaced14530056f39fd2b62aed3775d827%2F1%2Ftransformers%2520rise%2520of%2520the%2520beasts%2Fn%2Fn%2FTransformers.Rise.of.the.Beasts.2023.BluRay.2160p.UHD.MULTi.REMUX.HEVC.%2810bit%29.DV.Atmos.DTS-HD.MA.7.1-LEGi0N.mkv&videoCodecs=h264&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=32 500 (Internal Server Error)
Player.js:114 Player {code: 83, message: 'Video is not supported', critical: true, error: MediaError}code: 83critical: trueerror: MediaErrorcode: 4message: "MEDIA_ELEMENT_ERROR: Format error"[[Prototype]]: MediaErrorMEDIA_ERR_ABORTED: 1MEDIA_ERR_DECODE: 3MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: (...)message: (...)constructor: ƒ MediaError()Symbol(Symbol.toStringTag): "MediaError"get code: ƒ code()get message: ƒ message()[[Prototype]]: Objectmessage: "Video is not supported"[[Prototype]]: Object
(anonymous) @ Player.js:114
(anonymous) @ index.js:181
I @ useVideo.js:108
(anonymous) @ index.js:181
(anonymous) @ StremioVideo.js:52
(anonymous) @ index.js:181
(anonymous) @ withStreamingServer.js:48
(anonymous) @ index.js:181
(anonymous) @ withHTMLSubtitles.js:93
(anonymous) @ index.js:181
N @ HTMLVideo.js:349
(anonymous) @ HTMLVideo.js:343
S.S.onerror @ HTMLVideo.js:28
error (async)
S @ HTMLVideo.js:27
t @ withHTMLSubtitles.js:14
t @ withStreamingServer.js:17
T.dispatch @ StremioVideo.js:47
_ @ useVideo.js:47
load @ useVideo.js:58
(anonymous) @ Player.js:293
i_ @ react-dom.production.min.js:243
LT @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
L @ scheduler.production.min.js:13
g @ scheduler.production.min.js:14
processImmediate @ node:internal/timers:476
Show 20 more frames
Show less
```
Now i will try flatpak stremio-service

**Comment by SHADOW-REX** [comment]
- Tried the unbundled appimage with flatpak stremio service ( same result)
- Tried stremio web (same result)
Ig stremio enhanced is just not meant for me :(

**Comment by REVENGE977** [comment]
> Tried stremio web (same result)

That confirms the issue is from Stremio Service, not Enhanced. [You can report the issue in the official Stremio Service repository from here](https://github.com/Stremio/stremio-service/issues)

There is a last resort solution:
- Launch the official Stremio app (assuming that everything works fine there)
- Run Stremio Enhanced using the --no-stremio-service flag (like this: `./stremio-enhanced --no-stremio-service`)

This will run Stremio Enhanced but it will use the same streaming server that's in the official app.

Make sure you open the official app first then Enhanced and in the settings make sure you have Online status in the Streaming tab.

**Comment by REVENGE977** [comment]
I will close the issue since it's not related to Stremio Enhanced but Stremio Service. If you need more help, you can join my discord server. The link is in my profile.
